l_english:
 ####---------- General Script Value Descriptions ----------####
 kog_value_from_base: "Base Value"
 kog_value_from_base_progress: "Base Monthly Progress"
 kog_value_from_base_decay: "Base Monthly Decay"
 kog_value_from_national_piety: "the [concept_national_piety] of [ROOT.GetCountry.GetNameNoFlag]"
 kog_value_from_active_religion_law: "the active [GetLawGroup('lawgroup_church_and_state').GetName] [concept_law] in [ROOT.GetCountry.GetNameNoFlag]"
 kog_value_from_canon_law_compliance: "[ROOT.GetCountry.GetNameNoFlag]'s compliance with the $kog_canon_laws$ of the [ROOT.GetCountry.GetStateReligion.GetName] Church"
 
 
 ####---------- Canon Law Script Value Descriptions ----------####
 kog_value_from_investiture_compliance: "#indent_newline:3 having [GetPlayer.GetActiveLawFromGroup('lawgroup_investiture').GetName] enacted in [GetPlayer.GetNameNoFlag] while [GetPlayer.MakeScope.Var('kog_global_faith_journal_var').Var('kog_canon_law_statism_var').GetFlagName] is an active [concept_canon_law]#!"
 kog_value_from_land_reform: "#indent_newline:3 having [GetPlayer.GetActiveLawFromGroup('lawgroup_land_reform').GetName] enacted in [GetPlayer.GetNameNoFlag] while [GetPlayer.MakeScope.Var('kog_global_faith_journal_var').Var('kog_canon_law_social_role_var').GetFlagName] is an active [concept_canon_law]#!"
 kog_value_from_schooling: "#indent_newline:3 the amount of [Concept('concept_investment_level', '$concept_investment_levels$')] into the [GetInstitutionType('institution_schools').GetName] [concept_institution] while [GetPlayer.MakeScope.Var('kog_global_faith_journal_var').Var('kog_canon_law_social_role_var').GetFlagName] is an active [concept_canon_law]#!"
 kog_value_from_labor_rights: "#indent_newline:3 the amount of [Concept('concept_investment_level', '$concept_investment_levels$')] into the [GetInstitutionType('institution_workplace_safety').GetName] [concept_institution] while [GetPlayer.MakeScope.Var('kog_global_faith_journal_var').Var('kog_canon_law_social_role_var').GetFlagName] is an active [concept_canon_law]#!"
 kog_value_from_womens_rights: "#indent_newline:3 having [GetPlayer.GetActiveLawFromGroup('lawgroup_rights_of_women').GetName] enacted in [GetPlayer.GetNameNoFlag] while [GetPlayer.MakeScope.Var('kog_global_faith_journal_var').Var('kog_canon_law_statism_var').GetFlagName] is an active [concept_canon_law]#!"
 kog_value_from_clerical_universities: "#indent_newline:3 the number of [GetBuildingType('building_university').GetName] [Concept('concept_building_level', '$concept_building_levels$s')] in [GetPlayer.GetNameNoFlag] with the #bold $pm_religious_academia$#! [concept_production_method] active#!"
 kog_value_from_academic_universities: "#indent_newline:3 the number of [GetBuildingType('building_university').GetName] [Concept('concept_building_level', '$concept_building_levels$s')] in [GetPlayer.GetNameNoFlag] with the #bold $pm_secular_academia$#! [concept_production_method] active#!"
 kog_value_from_literacy_rate: "#indent_newline:3 the average [concept_literacy] rate in [GetPlayer.GetNameNoFlag]#!"
 kog_value_from_schismatic: "being in [concept_schism]"
 kog_value_from_autocephaly: "having [concept_autocephaly]"
 
 ####---------- Schism Script Value Descriptions ----------####
 kog_value_from_ignoring_dissent: "Ignoring Dissenters"
 kog_value_from_purged_ecclesiarchy: "Purging Greek Bishops"
 kog_value_from_fast_tracking_bishops: "Fast Tracking New Bishops"
 kog_value_from_conceded_to_traditionalists: "Conceding to Traditionalist Grievances"
 kog_value_from_retained_ecclesiarchy: "Retaining Greek Bishops"
 kog_value_from_monk_smackdown: "Tolerating Monk Brawls"
 kog_value_from_agitator_delay: "Agitator Delaying Procedures"
 
 
 ####---------- Ecumenical Council Script Value Descriptions ----------####
 kog_value_from_italian_states: "[Concept('concept_state','$concept_states$')] in the [GetStrategicRegion('geographic_region_italy_old').GetName] [concept_strategic_region]"
 kog_value_from_european_states: "[Concept('concept_state','$concept_states$')] in the [GetStrategicRegion('geographic_region_england_old').GetName], [GetStrategicRegion('geographic_region_iberia_old').GetName], [GetStrategicRegion('geographic_region_france_old').GetName], [GetStrategicRegion('geographic_region_occitania_old').GetName], [GetStrategicRegion('geographic_region_rhine_old').GetName], [GetStrategicRegion('geographic_region_north_germany_old').GetName], [GetStrategicRegion('geographic_region_south_germany_old').GetName], or [GetStrategicRegion('geographic_region_poland_old').GetName], [concept_strategic_region]"
 kog_value_from_other_states: "non-European [Concept('concept_state','$concept_states$')]"
 
 
 ####---------- Collegium Script Value Descriptions ----------####
 kog_value_from_persistent_trait: "having the trait [concept_character_trait] #bold Persistent#!"
 kog_value_from_arrogant_trait: "having the trait [concept_character_trait] #bold Arrogant#!"
 kog_value_from_bigoted_trait: "having the trait [concept_character_trait] #bold Bigoted#!"
 kog_value_from_tactful_trait: "having the trait [concept_character_trait] #bold Tactful#!"
 kog_value_from_ambitious_trait: "having the trait [concept_character_trait] #bold Ambitious#!"
 kog_value_from_wrathful_trait: "having the trait [concept_character_trait] #bold Wrathful#!"
 kog_value_from_reserved_trait: "having the trait [concept_character_trait] #bold Reserved#!"
 kog_value_from_cruel_trait: "having the trait [concept_character_trait] #bold Cruel#!"
 kog_value_from_meticulous_trait: "having the trait [concept_character_trait] #bold Meticulous#!"
 kog_value_from_charismatic_trait: "having the trait [concept_character_trait] #bold Charismatic#!"
 kog_value_from_brave_trait: "having the trait [concept_character_trait] #bold Brave#!"
 kog_value_from_innovative_trait: "having the trait [concept_character_trait] #bold Innovative#!"
 kog_value_from_hedonist_trait: "having the trait [concept_character_trait] #bold Hedonist#!"
 kog_value_from_pious_trait: "having the trait [concept_character_trait] #bold Pious#!"
 kog_value_from_honorable_trait: "having the trait [concept_character_trait] #bold Honorable#!"
 kog_value_from_ruthless_trait: "having the trait [concept_character_trait] #bold Ruthless#!"
 kog_value_from_compliant_trait: "having the trait [concept_character_trait] #bold Compliant#!"
 kog_value_from_alcoholic_trait: "having the trait [concept_character_trait] #bold Alcoholic#!"
 kog_value_from_opium_addiction_trait: "having the trait [concept_character_trait] #bold Opium Addiction#!"
 kog_value_from_grifter_trait: "having the trait [concept_character_trait] #bold Grifter#!"
 kog_value_from_expensive_tastes_trait: "having the trait [concept_character_trait] #bold Expensive Tastes#!"
 kog_value_from_war_criminal_trait: "having the trait [concept_character_trait] #bold War Criminal#!"
 kog_value_from_political_appointee_trait: "having the trait [concept_character_trait] #bold Political Appointee#!"
 kog_value_from_inept_trait: "having the trait [concept_character_trait] #bold Inept#!"
 
 kog_value_from_home_prestige: "the [concept_prestige] of this character’s home [concept_country]"
 kog_value_from_italian_culture: "having an #bold Italian#! [concept_culture]"
 kog_value_from_prominence: "this character's [concept_prominence]"
 kog_value_from_piety: "this character’s [concept_personal_piety]"
 kog_value_from_age: "this character’s age"
 kog_value_from_being_underage: "being #bold Underage#!"
 
 
 ####---------- Encyclical Script Value Descriptions ----------####
 #//
 
 
 ####---------- Episcopal Seat Script Values ----------####
 kog_value_from_controls_rome: "$kog_controlling$ $kog_rome$"
 kog_value_from_controls_santiago: "$kog_controlling$ $kog_santiago$"
 kog_value_from_controls_paris: "$kog_controlling$ $kog_paris$"
 kog_value_from_controls_koln: "$kog_controlling$ $kog_koln$"
 kog_value_from_controls_vienna: "$kog_controlling$ $kog_vienna$"
 
 kog_value_from_controls_constantinople: "$kog_controlling$ $kog_constantinople$"
 kog_value_from_controls_antioch: "$kog_controlling$ $kog_antioch$"
 kog_value_from_controls_alexandria: "$kog_controlling$ $kog_alexandria$"
 kog_value_from_controls_jerusalem: "$kog_controlling$ $kog_jerusalem$"
 kog_value_from_controls_moscow: "$kog_controlling$ $kog_moscow$"
 
 kog_value_from_controls_coptic_alexandria: "$kog_controlling$ $kog_coptic_alexandria$"
 kog_value_from_controls_syriac_antioch: "$kog_controlling$ $kog_syriac_antioch$"
 kog_value_from_controls_etchmiadzin: "$kog_controlling$ $kog_etchmiadzin$"
 kog_value_from_controls_addis_ababa: "$kog_controlling$ $kog_addis_ababa$"
 kog_value_from_controls_konak: "$kog_controlling$ $kog_konak$"
 
 kog_value_from_controls_elysium: "$kog_controlling$ $kog_elysium$"
 kog_value_from_controls_tututepec: "$kog_controlling$ $kog_tututepec$"
 kog_value_from_controls_cahokia: "$kog_controlling$ $kog_cahokia$"
 
 kog_value_from_rome_opinion: "$kog_rome$'s opinion of [GetPlayer.GetNameNoFlag]"
 
 kog_value_from_diplomacy: "[concept_episcopal_seat] diplomatic efforts"
 kog_value_from_improving_relations: "improving relations with this [concept_episcopal_seat]"
 kog_value_from_damaging_relations: "damaging relations with this [concept_episcopal_seat]"
 
 kog_value_from_seat_integration: "#bold Integrating Episcopal Seats#!"
 kog_value_from_communion: "Remaining #bold #green In Communion#!#! with Constantinople"
 kog_value_from_swaying_seat: "Diplomatic Efforts"
 kog_value_from_controlling_seat: "Controlling this Seat"
 kog_value_from_controls_all_seats: "#bold Controlling all Episcopal Seats#!"
 kog_value_from_seat_control: "controlling this [concept_episcopal_seat]"
 kog_value_from_matching_religion: "share the same [concept_religion]"
 kog_value_from_matching_liturgical_rite: "sharing a [concept_liturgical_rite]"
 kog_value_from_relations: "our [concept_relations] with this [concept_episcopal_seat]"
 kog_value_from_different_religion: "differences in [concept_religion]"
 kog_value_from_differing_liturgical_rite: "differences in [concept_liturgical_rite]"
 kog_value_from_secularism_denounced: "a Patriarch Denouncing Our #bold Secular Policies#!"
 kog_value_from_mending_schism: "#bold Attempting to Mend the Great Schism#!"
 
 
 ####---------- Unsorted Localization ----------####
 kog_value_from_hosting_council: "#bold #khoine Hosting an Ecumenical Council#!#!"
 kog_value_from_has_icon: "#bold Having an Active Icon#!"
 
 kog_value_from_monarchy: "having #yellow Monarchy#! enacted"
 kog_value_from_theocracy: "having #yellow Theocracy#! enacted"
 kog_value_from_state_religion: "having [GetLawType('law_state_religion').GetName] enacted"
 kog_value_from_total_separation: "having [GetLawType('law_total_separation').GetName] enacted"
 kog_value_from_state_atheism: "having [GetLawType('law_state_atheism').GetName] enacted"
 kog_value_from_freedom_of_conscience: "having [GetLawType('law_freedom_of_conscience').GetName] enacted"
 kog_value_from_religious_schools: "having [GetLawType('law_religious_schools').GetName] enacted"
 kog_value_from_non_religious_schools: "having a non-[GetLawType('law_religious_schools').GetName] system in place"
 kog_value_from_charity_hospitals: "having [GetLawType('law_charitable_health_system').GetName] enacted"
 kog_value_from_non_charity_hospitals: "having a non-[GetLawType('law_charitable_health_system').GetName] system in place"