languages = {
	check = "english"
}

filter = {
    show_vanilla = no
    show_loaded_mods = no
}

load_mod = {
	label = "CMF"
	mod = "/home/alexedishi/IntelliJ-IDEA/IntelliJ-Projects/Community-Mod-Framework"
}

load_mod = {
	label = "ETF"
	mod = "/home/alexedishi/IntelliJ-IDEA/IntelliJ-Projects/Expanded-Topbar-Framework"
}